// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package dev.suka.grpc;

/**
 * Protobuf type {@code grpc.channelz.v1.Cerveja}
 */
public final class Cerveja extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:grpc.channelz.v1.Cerveja)
        CervejaOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use Cerveja.newBuilder() to construct.
  private Cerveja(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Cerveja() {
    nome_ = "";
    tipo_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
    return new Cerveja();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private Cerveja(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            nome_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            tipo_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return dev.suka.grpc.Mensagem.internal_static_grpc_channelz_v1_Cerveja_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return dev.suka.grpc.Mensagem.internal_static_grpc_channelz_v1_Cerveja_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    dev.suka.grpc.Cerveja.class, dev.suka.grpc.Cerveja.Builder.class);
  }

  /**
   * Protobuf enum {@code grpc.channelz.v1.Cerveja.TipoCerva}
   */
  public enum TipoCerva
          implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CERVEJA_NACIONAL = 0;</code>
     */
    CERVEJA_NACIONAL(0),
    /**
     * <code>CERVEJA_GRINGA = 1;</code>
     */
    CERVEJA_GRINGA(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CERVEJA_NACIONAL = 0;</code>
     */
    public static final int CERVEJA_NACIONAL_VALUE = 0;
    /**
     * <code>CERVEJA_GRINGA = 1;</code>
     */
    public static final int CERVEJA_GRINGA_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TipoCerva valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TipoCerva forNumber(int value) {
      switch (value) {
        case 0:
          return CERVEJA_NACIONAL;
        case 1:
          return CERVEJA_GRINGA;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TipoCerva>
    internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            TipoCerva> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TipoCerva>() {
              public TipoCerva findValueByNumber(int number) {
                return TipoCerva.forNumber(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return dev.suka.grpc.Cerveja.getDescriptor().getEnumTypes().get(0);
    }

    private static final TipoCerva[] VALUES = values();

    public static TipoCerva valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
                "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TipoCerva(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:grpc.channelz.v1.Cerveja.TipoCerva)
  }

  public static final int NOME_FIELD_NUMBER = 1;
  private volatile java.lang.Object nome_;

  /**
   * <code>string nome = 1;</code>
   *
   * @return The nome.
   */
  @java.lang.Override
  public java.lang.String getNome() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nome_ = s;
      return s;
    }
  }

  /**
   * <code>string nome = 1;</code>
   *
   * @return The bytes for nome.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getNomeBytes() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      nome_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIPO_FIELD_NUMBER = 3;
  private int tipo_;

  /**
   * <code>.grpc.channelz.v1.Cerveja.TipoCerva tipo = 3;</code>
   *
   * @return The enum numeric value on the wire for tipo.
   */
  @java.lang.Override
  public int getTipoValue() {
    return tipo_;
  }

  /**
   * <code>.grpc.channelz.v1.Cerveja.TipoCerva tipo = 3;</code>
   *
   * @return The tipo.
   */
  @java.lang.Override
  public dev.suka.grpc.Cerveja.TipoCerva getTipo() {
    @SuppressWarnings("deprecation")
    dev.suka.grpc.Cerveja.TipoCerva result = dev.suka.grpc.Cerveja.TipoCerva.valueOf(tipo_);
    return result == null ? dev.suka.grpc.Cerveja.TipoCerva.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (!getNomeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
    }
    if (tipo_ != dev.suka.grpc.Cerveja.TipoCerva.CERVEJA_NACIONAL.getNumber()) {
      output.writeEnum(3, tipo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNomeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
    }
    if (tipo_ != dev.suka.grpc.Cerveja.TipoCerva.CERVEJA_NACIONAL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
              .computeEnumSize(3, tipo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof dev.suka.grpc.Cerveja)) {
      return super.equals(obj);
    }
    dev.suka.grpc.Cerveja other = (dev.suka.grpc.Cerveja) obj;

    if (!getNome()
            .equals(other.getNome())) return false;
    if (tipo_ != other.tipo_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NOME_FIELD_NUMBER;
    hash = (53 * hash) + getNome().hashCode();
    hash = (37 * hash) + TIPO_FIELD_NUMBER;
    hash = (53 * hash) + tipo_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.suka.grpc.Cerveja parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static dev.suka.grpc.Cerveja parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static dev.suka.grpc.Cerveja parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static dev.suka.grpc.Cerveja parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static dev.suka.grpc.Cerveja parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static dev.suka.grpc.Cerveja parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static dev.suka.grpc.Cerveja parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static dev.suka.grpc.Cerveja parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.suka.grpc.Cerveja parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.suka.grpc.Cerveja parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.suka.grpc.Cerveja parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static dev.suka.grpc.Cerveja parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(dev.suka.grpc.Cerveja prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code grpc.channelz.v1.Cerveja}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:grpc.channelz.v1.Cerveja)
          dev.suka.grpc.CervejaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return dev.suka.grpc.Mensagem.internal_static_grpc_channelz_v1_Cerveja_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return dev.suka.grpc.Mensagem.internal_static_grpc_channelz_v1_Cerveja_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      dev.suka.grpc.Cerveja.class, dev.suka.grpc.Cerveja.Builder.class);
    }

    // Construct using dev.suka.grpc.Cerveja.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      nome_ = "";

      tipo_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return dev.suka.grpc.Mensagem.internal_static_grpc_channelz_v1_Cerveja_descriptor;
    }

    @java.lang.Override
    public dev.suka.grpc.Cerveja getDefaultInstanceForType() {
      return dev.suka.grpc.Cerveja.getDefaultInstance();
    }

    @java.lang.Override
    public dev.suka.grpc.Cerveja build() {
      dev.suka.grpc.Cerveja result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.suka.grpc.Cerveja buildPartial() {
      dev.suka.grpc.Cerveja result = new dev.suka.grpc.Cerveja(this);
      result.nome_ = nome_;
      result.tipo_ = tipo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.suka.grpc.Cerveja) {
        return mergeFrom((dev.suka.grpc.Cerveja) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.suka.grpc.Cerveja other) {
      if (other == dev.suka.grpc.Cerveja.getDefaultInstance()) return this;
      if (!other.getNome().isEmpty()) {
        nome_ = other.nome_;
        onChanged();
      }
      if (other.tipo_ != 0) {
        setTipoValue(other.getTipoValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      dev.suka.grpc.Cerveja parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dev.suka.grpc.Cerveja) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object nome_ = "";

    /**
     * <code>string nome = 1;</code>
     *
     * @return The nome.
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string nome = 1;</code>
     *
     * @return The bytes for nome.
     */
    public com.google.protobuf.ByteString
    getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string nome = 1;</code>
     *
     * @param value The nome to set.
     * @return This builder for chaining.
     */
    public Builder setNome(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      nome_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string nome = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearNome() {

      nome_ = getDefaultInstance().getNome();
      onChanged();
      return this;
    }

    /**
     * <code>string nome = 1;</code>
     *
     * @param value The bytes for nome to set.
     * @return This builder for chaining.
     */
    public Builder setNomeBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      nome_ = value;
      onChanged();
      return this;
    }

    private int tipo_ = 0;

    /**
     * <code>.grpc.channelz.v1.Cerveja.TipoCerva tipo = 3;</code>
     *
     * @return The enum numeric value on the wire for tipo.
     */
    @java.lang.Override
    public int getTipoValue() {
      return tipo_;
    }

    /**
     * <code>.grpc.channelz.v1.Cerveja.TipoCerva tipo = 3;</code>
     *
     * @param value The enum numeric value on the wire for tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipoValue(int value) {

      tipo_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>.grpc.channelz.v1.Cerveja.TipoCerva tipo = 3;</code>
     *
     * @return The tipo.
     */
    @java.lang.Override
    public dev.suka.grpc.Cerveja.TipoCerva getTipo() {
      @SuppressWarnings("deprecation")
      dev.suka.grpc.Cerveja.TipoCerva result = dev.suka.grpc.Cerveja.TipoCerva.valueOf(tipo_);
      return result == null ? dev.suka.grpc.Cerveja.TipoCerva.UNRECOGNIZED : result;
    }

    /**
     * <code>.grpc.channelz.v1.Cerveja.TipoCerva tipo = 3;</code>
     *
     * @param value The tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipo(dev.suka.grpc.Cerveja.TipoCerva value) {
      if (value == null) {
        throw new NullPointerException();
      }

      tipo_ = value.getNumber();
      onChanged();
      return this;
    }

    /**
     * <code>.grpc.channelz.v1.Cerveja.TipoCerva tipo = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearTipo() {

      tipo_ = 0;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.channelz.v1.Cerveja)
  }

  // @@protoc_insertion_point(class_scope:grpc.channelz.v1.Cerveja)
  private static final dev.suka.grpc.Cerveja DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new dev.suka.grpc.Cerveja();
  }

  public static dev.suka.grpc.Cerveja getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Cerveja>
          PARSER = new com.google.protobuf.AbstractParser<Cerveja>() {
    @java.lang.Override
    public Cerveja parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new Cerveja(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Cerveja> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Cerveja> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.suka.grpc.Cerveja getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

