// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package dev.suka.grpc;

public interface CervejaOrBuilder extends
        // @@protoc_insertion_point(interface_extends:grpc.channelz.v1.Cerveja)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     *
     * @return The nome.
     */
    java.lang.String getNome();

    /**
     * <code>string nome = 1;</code>
     *
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
    getNomeBytes();

    /**
     * <code>.grpc.channelz.v1.Cerveja.TipoCerva tipo = 3;</code>
     *
     * @return The enum numeric value on the wire for tipo.
     */
    int getTipoValue();

    /**
     * <code>.grpc.channelz.v1.Cerveja.TipoCerva tipo = 3;</code>
     *
     * @return The tipo.
     */
    dev.suka.grpc.Cerveja.TipoCerva getTipo();
}
