// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package dev.suka.grpc;

public final class Mensagem {
    private Mensagem() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_grpc_channelz_v1_Cerveja_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_grpc_channelz_v1_Cerveja_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016mensagem.proto\022\020grpc.channelz.v1\032\033goog" +
                        "le/protobuf/empty.proto\"\201\001\n\007Cerveja\022\014\n\004n" +
                        "ome\030\001 \001(\t\0221\n\004tipo\030\003 \001(\0162#.grpc.channelz." +
                        "v1.Cerveja.TipoCerva\"5\n\tTipoCerva\022\024\n\020CER" +
                        "VEJA_NACIONAL\020\000\022\022\n\016CERVEJA_GRINGA\020\0012M\n\nC" +
                        "ervejeiro\022?\n\ngetCerveja\022\026.google.protobu" +
                        "f.Empty\032\031.grpc.channelz.v1.CervejaBE\n\rde" +
                        "v.suka.grpcP\001Z2google.golang.org/grpc/bi" +
                        "narylog/grpc_binarylog_v1b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.EmptyProto.getDescriptor(),
                        });
        internal_static_grpc_channelz_v1_Cerveja_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_grpc_channelz_v1_Cerveja_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_grpc_channelz_v1_Cerveja_descriptor,
                new java.lang.String[]{"Nome", "Tipo",});
        com.google.protobuf.EmptyProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
